#!/bin/bash

SUBMIT=1
# Check versions.gradle updated before submitting a new commit
if [ -f $ANDROID_PROJECT_VERSION_FILE ]
then
    GIT_ROOT=`git rev-parse --show-toplevel`
    VERSION_DIFF=`diff $GIT_ROOT/versions.gradle $ANDROID_PROJECT_VERSION_FILE`
    if [[ $# -eq 0 && -z $VERSION_DIFF ]]; then
        SUBMIT=0
    else
        echo "versions.gradle has new updates, please sync with the latest before commit"
        echo "cp \$ANDROID_PROJECT_VERSION_FILE versions.gradle"
        SUBMIT=1
    fi
fi
exit $SUBMIT
